# Generated by Django 3.0.7 on 2020-09-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoset',
            fields=[
                ('auto_num', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=45)),
                ('sname', models.CharField(max_length=45)),
                ('set_money', models.FloatField()),
                ('today', models.FloatField()),
                ('input', models.FloatField()),
                ('output', models.FloatField()),
                ('profit', models.FloatField()),
                ('flag', models.IntegerField()),
                ('strat_date', models.CharField(max_length=45)),
                ('end_date', models.CharField(max_length=45)),
                ('autosetcol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'autoset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('simul_num', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=45)),
                ('sname', models.CharField(max_length=45)),
                ('set_money', models.FloatField()),
                ('today', models.FloatField()),
                ('input', models.FloatField()),
                ('output', models.FloatField()),
                ('profit', models.FloatField()),
                ('start_date', models.CharField(max_length=45)),
                ('end_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'simulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockitem',
            fields=[
                ('stock_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('representative', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('numofstock', models.FloatField(db_column='numOfstock')),
                ('probabilitytowin', models.FloatField(db_column='probabilitytoWin')),
                ('probabilitytolose', models.FloatField(db_column='probabilitytoLose')),
            ],
            options={
                'db_table': 'stockitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictRate',
            fields=[
                ('stock_num', models.OneToOneField(db_column='stock_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ergate.Stockitem')),
                ('name', models.CharField(max_length=45)),
                ('numofstock', models.FloatField(db_column='numOfstock')),
                ('persent', models.FloatField()),
            ],
            options={
                'db_table': 'predict_rate',
                'managed': False,
            },
        ),
    ]
